server:
  port: 10086

spring:
  application:
    name: enhance-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # enable service discovery
          route-id-prefix: base_discovery
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "docs.spring.io"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - HEAD
            - OPTIONS
            - PATCH
      routes:
      - id: basic-service
        uri: lb://basic-service
        predicates:
        - Path=/basic/**
        filters:
        - RewritePath=/basic/(?<path>.*), /$\{path}
        - AddRequestHeader=X-Request-Foo, Bar
        - name: Retry
          args:
            retries: 5
            statuses:
              - SERVICE_UNAVAILABLE
              - REQUEST_TIMEOUT
            series:
              - SERVER_ERROR
              - CLIENT_ERROR

      httpclient:
        connect-timeout: 300
        response-timeout: 3M
        pool:
          name: gateway-http-proxy
          max-connections: 30
        ssl:
          use-insecure-trust-manager: false

    config:
      enabled: false

  # mongodb config
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: enhance-gateway

eureka:
  client:
    service-url:
      defaultZone: http://192.168.21.108:10061/eureka/

# configuration of the actuator endpoints
management:
  metrics:
    export:
      prometheus: # prometheus configuration
        enabled: true
        descriptions: true
        step: 1m
  endpoint:
    gateway:
      enabled: true
    prometheus:
      enabled: true
    threaddump:
      enabled: true
    restart:
      enabled: true # POST method ${hostname}/actuator/restart
    shutdown:
      enabled: true # POST method ${hostname}/actuator/shutdown
  endpoints:
    web:
      exposure:
        include: "*" # enable all endpoints

logging:
  level:
    org.iblog: trace
#    org: trace

enhance-gateway:
  http-client:
    config:
      connectTimeout: 2000
      socketTimeout: -1
      connectionRequestTimeout: -1
      maxTotal: 30
      maxPerRoute: 5
  x-task-scheduler:
    pollPause: 10000
    poolSize: 5
    nameSuffix: async-works
    queueName: schedulable-works-queue
    maxReties: 10
